name: build and deploy next js

on:
  push:
    branches: [ main ]

env:
    IMAGE_NAME: nextjs-app
    REGISTRY: touristwebregistry.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
        - name: checkout code
          uses: actions/checkout@v3

        - name: Login to azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Login to Azure Container Registry
          run: |
            az acr login --name touristwebregistry

        - name: Build docker image
          run: |
            docker build -t $REGISTRY/$IMAGE_NAME:latest -f docker/dockerfile .
            docker push $REGISTRY/$IMAGE_NAME:latest

        - name: Deploy to VM1
          uses: appleboy/ssh-action@v0.1.10
          with:
            host: ${{ secrets.VM1_PUBLIC_IP }}
            username: ${{ secrets.VM1_USERNAME }}
            key: ${{ secrets.VM1_SSH_KEY }}
            script: |
              docker pull $REGISTRY/$IMAGE_NAME:latest
              docker stop nextjs-app || true
              docker rm nextjs-app || true
              docker run -d --name nextjs-app -p 80:3000 $REGISTRY/$IMAGE_NAME:latest

        - name: Deploy to VM2
          uses: appleboy/ssh-action@v0.1.10
          with:
            host: ${{ secrets.VM2_PUBLIC_IP }}
            username: ${{ secrets.VM2_USERNAME }}
            key: ${{ secrets.VM2_SSH_KEY }}
            script: |
              docker pull $REGISTRY/$IMAGE_NAME:latest
              docker stop nextjs-app || true
              docker rm nextjs-app || true
              docker run -d --name nextjs-app -p 80:3000 $REGISTRY/$IMAGE_NAME:latest
            