name: build and deploy next js

on:
  push:
    branches: [ main ]

env:
    IMAGE_NAME: nextjs-app
    REGISTRY: ghcr.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - vm_host: ${{ secrets.VM1_PUBLIC_IP }}
            vm_username_secret: ${{ secrets.VM1_USERNAME }}
            vm_ssh_key_secret: ${{ secrets.VM1_SSH_KEY }}
          - vm_host: ${{ secrets.VM2_PUBLIC_IP }}
            vm_username_secret: ${{ secrets.VM2_USERNAME }}
            vm_ssh_key_secret: ${{ secrets.VM2_SSH_KEY }}

    steps:
        - name: checkout code
          uses: actions/checkout@v3

        - name: Login to azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Build docker image
          run: |
            docker push $REGISTRY/$IMAGE_NAME:latest

        - name: Deploy to VM
          uses: appleboy/ssh-action@v0.1.10
          with:
            host: ${{ matrix.vm_host }}
            username: ${{ secrets[matrix.vm_username_secret] }}
            key: ${{ secrets[matrix.vm_ssh_key_secret] }}
            script: |
              docker pull $REGISTRY/$IMAGE_NAME:latest
              docker stop nextjs-app || true
              docker rm nextjs-app || true
              docker run -d --name nextjs-app -p 80:3000 $REGISTRY/$IMAGE_NAME:latest
            